base_url = "https://naecoo.github.io"

title = "Naeco's blog"

author = "naeco"

theme = "kita"

default_language = "en"

generate_feed = true

feed_filename = "atom.xml"

taxonomies = [{ name = "tags", rss = true, feed = true, paginate_by = 5 }]

compile_sass = true

build_search_index = false

[markdown]
highlight_code = true

extra_syntaxes_and_themes = []

[extra]
# Enable KaTex math formula support globally.
math = false
# Enable mermaid support globally.
mermaid = true
# Enable comment support globally.
comment = false

# The profile on home page.
[extra.profile]
name = "Naeco"
bio = "Go big or go home."
avatar_url = "icons/github.svg"
avatar_invert = true

# The social icons below the profile on the home page.
[[extra.profile.social]]
name = "github"
url = "https://github.com/naecoo"

[[extra.profile.social]]
name = "email"
url = "mailto:ocean7hy@gmail.com"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

# The top menu.
#[[extra.menu]]
#name = "Projects"
#url = "$BASE_URL/projects"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

#[[extra.menu]]
#name = "About"
#url = "$BASE_URL/about"

# The page footer options.
#[extra.footer]
#since = 2020
#license = "CC BY-SA 4.0"
#license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

